# Generated by Django 5.0.6 on 2024-06-23 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
